### ISSUE TITLE
Question: where is the dask graph built?

### ISSUE THREAD

**Issue by GaelVaroquaux** [mrocklin/dask-learn#2]
Hi,

I was looking at the code in grid_search.py to understand how things work, and I am really dense: I don't understand where is the dask graph built.

It seems to me that _fit_and_score does not do any delayed evaluation and directly runs the estimation. When I look at line 67, where the for loop is run, the call is not protected. Actually, the usage of dask is tiny in this codebase, pretty much limited to line 75, which seems to me to be an execution of the dask graph. But nothing before seems to built the graph

Thus I do not understand how this work. Is it because dask arrays are passed in, and thus they trace what happens to them in the estimator? In which case I fear that this will work only in a small number of estimators.

**Comment by mrocklin** [comment]
Moving conversation to https://github.com/blaze/dask/pull/743#issuecomment-142313725
